### ISSUE TITLE
Terminal does not work

### ISSUE THREAD

**Issue by sboesebeck** [ldelossa/nvim-ide#10]
when opening the terminal panel, no shell is shown, just an empty editor pane.No error shown.

I do have `ToggleTerm` installed - maybe related...

**Comment by ldelossa** [comment]
How are you trying to open a terminal? You need to usr the "TerminalBrowser" component to do this.

**Comment by sboesebeck** [comment]
Yes... I was before...

Now the error is different (i do not know, what changed that). When calling `:Workspace` -> `Terminal Browser` -> `new` just nothing happens.

**Comment by sboesebeck** [comment]
And: when I toggle the bottom pane, I see commits there?!?! Seems I messed it up somehow

**Comment by sboesebeck** [comment]
I am not sure if it is related, but I got the error "Cannot open git - too many open files" when toggling between Panels.

**Comment by sboesebeck** [comment]
I messed up the config - my bad!

**Comment by ldelossa** [comment]
Glad you figured it out :)
