### ISSUE TITLE
Error on neovim exit

### ISSUE THREAD

**Issue by AlwaysIngame** [ldelossa/nvim-ide#106]
I am getting an error using this plugin, it's related to the terminal
I am using the default configuration.

Steps to produce:
1. Open nvim (nvim-ide opens left panel)
2. Open a terminal from the terminal browser
3. :qa close neovim
4. See an error in the terminal

This is the error:
`Error detected while processing TermClose Autocommands for "*":
Error executing lua callback: ...al/share/nvim/lazy/nvim-ide/lua/ide/trees/marshaller.lua:124: Failed to delete line
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	...al/share/nvim/lazy/nvim-ide/lua/ide/trees/marshaller.lua:124: in function 'marshal'
	...n/.local/share/nvim/lazy/nvim-ide/lua/ide/trees/tree.lua:263: in function 'marshal'
	...ua/ide/components/terminal/terminalbrowser/component.lua:76: in function 'refresh'
	...ua/ide/components/terminal/terminalbrowser/component.lua:104: in function <...ua/ide/components/terminal/terminalbrowser/component.lua:101>`

Not sure what it means, and it doesn't affect my usage of this plugin anyway except that the error looks annoying

**Comment by AlwaysIngame** [comment]
I should also mention that the error appears once for every terminal that is open.

**Comment by ldelossa** [comment]
Hmm, this seems like a weird timing bug. 

Can you try again with the latest commit I just pushed?

**Comment by AlwaysIngame** [comment]
I am still getting the same error

**Comment by AlwaysIngame** [comment]
I actually get a similar error without opening a terminal. Sometimes when I close neovim I see this erro multiple times in my terminal:
`Error executing vim.schedule lua callback: ...al/share/nvim/lazy/nvim-ide/lua/ide/trees/marshaller.lua:124: Failed to delete line
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	...al/share/nvim/lazy/nvim-ide/lua/ide/trees/marshaller.lua:124: in function 'marshal'
	...n/.local/share/nvim/lazy/nvim-ide/lua/ide/trees/tree.lua:263: in function 'marshal'
	.../lazy/nvim-ide/lua/ide/components/explorer/component.lua:252: in function 'expand'
	.../lazy/nvim-ide/lua/ide/components/explorer/component.lua:208: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>`

**Comment by ldelossa** [comment]
Yeah, Im thinking this is a timing bug netween the termclose event firing and something with the buffer. 

The issue for me is it doesnt happen all the time, tho I have seen it. May need a bit to debug this one.

**Comment by ldelossa** [comment]
@AlwaysIngame - Can you try again with latest commit? I did the hacky thing and just wrapped it in a try/catch lua equivalent.

**Comment by AlwaysIngame** [comment]
Yea that seems to fix the issue related to having an open terminal.
I'll keep using the plugin and see if this issue ever comes up again. Thanks
