### ISSUE TITLE
newlines in Outline causing error

### ISSUE THREAD

**Issue by hbak** [ldelossa/nvim-ide#108]
in ide.trees.marshaller.lua, where the tree writes itself out:
`        vim.api.nvim_buf_set_lines(Tree.buffer, 0, #self.buffer_lines, false, self.buffer_lines)
`

There seems a possibility where self.buffer_lines can contain newlines, and nvim_buf_set_lines doesn't seem to like when the buffer has '\n'.   To temporarily stop/debug the error, right before the line above, I check each line for \n and replace each occurrance with \<NEWLINE\>.
![image](https://user-images.githubusercontent.com/1242201/211913985-91977915-2f7a-4ac2-a977-979f68b0519a.png)

Based on your own understanding of how the outline component works, should newlines be allowed through here?

**Comment by ldelossa** [comment]
Oh interesting! This is the first time ive seen newlines in the LSP response for symbols. 

By any chance so you know how vscode handles this? 

It will def break nvim-ide, we probably want to filter them out and replace with a space or something similar

**Comment by hbak** [comment]
Yeah, it felt like a weird case.   Sorry, I have no idea how vscode handles it.
Me, being impulsive, just did this:

```
for i, line in ipairs(self.buffer_lines) do
	self.buffer_lines[i] = [line](line:gsub('\n%s*', ''))
end
```

![image](https://user-images.githubusercontent.com/1242201/211929385-d238c1f8-be20-4a41-95cf-0e4deff6d611.png)

(notice "vim.lsp.diagnostic")

**Comment by ldelossa** [comment]
What language sever is this? And can you link me to that block of code if its public?

**Comment by hbak** [comment]
lol!   I've just discovered it's code that I've taken from a Reddit comment posted by... you!
https://www.reddit.com/r/neovim/comments/og1cdv/comment/h4gzvvv/

LSP is sumneko_lua.

**Comment by ldelossa** [comment]
lol. But how does that bit of code have to do with the outline component? 

P.s. i use this now: https://github.com/ldelossa/dotfiles/blob/5f149b92de9ed1c5a6a8759069dbc20f43aa17ff/config/nvim/plugs.vim#L60 lol

**Comment by hbak** [comment]
Oh sorry, your Reddit comment I posted is the block of code that caused the multi-line LSP node with Sumneko
```
local diags = vim
  .lsp
  .diagnostic
  .get_line_diagnostics(...)
```

**Comment by ldelossa** [comment]
@hbak should be fixed now.
