### ISSUE TITLE
Default panel width

### ISSUE THREAD

**Issue by prdanelli** [ldelossa/nvim-ide#13]
I've found a few "issues" while testing and i'm adding them individually so as to keep the discussions focused. 

Is it possible to set a wider default width for the panels?

**Comment by ldelossa** [comment]
Yeah this is needed.

**Comment by distek** [comment]
@ldelossa would you accept a PR for this?

**Comment by ldelossa** [comment]
Yup. The window layout chord is notoriously tricky, it all takes place in the Panel class's open() function.
