### ISSUE TITLE
Issues closing Nvim/Buffers

### ISSUE THREAD

**Issue by prdanelli** [ldelossa/nvim-ide#14]
I've found a few "issues" while testing and i'm adding them individually so as to keep the discussions focused. 

+ Just noticed `:q` on a buffer, which would normally close Nvim, seems to close the buffers, but keeps the left and right panels open, which need to be individually closed.

+ Closing a buffer, with the panels open, means that the panels take up the entire viewport, then when I try to move to another buffer, it opens inside one of the IDE panels.

**Comment by mrjones2014** [comment]
Same issue here, I think what we're asking for is, when closing a window, if the only remaining windows are all from nvim-ide, then close Neovim completely.

**Comment by prdanelli** [comment]
At the moment, the bigger issue for me is that when you close the buffer with the panels open, `bnext` opens the panel in the to left panel.

**Comment by ldelossa** [comment]
The panels are normal Neovim windows. So use ":qa" instead. Just like if you had multiple neovim windows open and wanted to quit.

**Comment by distek** [comment]
This seems to work well for me:
```lua
vim.api.nvim_create_autocmd("QuitPre", {
    pattern = {
        "*"
    },
    callback = function()
        -- close the current window as expected
        vim.cmd("wincmd c")

        local exit = true

        for _, v in ipairs(vim.api.nvim_list_wins()) do
            local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))

            -- I kept getting an unnamed, empty, buffer for some reason, hence name == ""
            if string.find(name, "component://*") or name == "" then
                goto continue
            end

            -- lua's weird
            -- needed this to make compiler happy
            if true then
                exit = false
                break
            end

            ::continue::
        end

        if exit then
            vim.cmd("qa")
        end
    end
})
```

**Comment by ldelossa** [comment]
Ohhh this is cute. Hmm maybe this is worth adding to the WorkspaceController on start? Hide it behind a config flag like "auto_close" or something?

**Comment by mrjones2014** [comment]
Yeah, same idea as how nvim-tree has an option to close Neovim if it’s the last window

**Comment by distek** [comment]
I think the one I wrote there could be a bit more robust. Also I'm starting to think QuitPre might be the wrong event to track. I can't actually `:qa` anymore unless it's strictly one remaining window + the panels.

**Comment by mrjones2014** [comment]
Yeah I think you want to use `WinClosed`

**Comment by distek** [comment]
With WinClosed, it will trigger on _any_ window being closed, including completion windows, Noice's propmpts, etc.

I'm not really sure what the best way to handle this is.

**Comment by ldelossa** [comment]
You could still catch the WinClosed event, but when you catch it, list all windows, search thru  them, and if the only buffers you find in those Windows start with "component://" you can quit vim at that point.

Its a brute force approach but i  think it  will work.

**Comment by distek** [comment]
This seems to work as expected:

```lua
vim.api.nvim_create_autocmd("WinClosed", {
    pattern = {
        "*"
    },

    callback = function()
        vim.cmd("wincmd c")

        local stdBufCount = 0
        for _, v in ipairs(vim.api.nvim_list_wins()) do
            local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))

            if string.find(name, "component://*") then
                goto continue
            end

            stdBufCount = stdBufCount + 1

            ::continue::
        end

        if stdBufCount == 0 then
            vim.cmd("qa")
        end
    end
})

```

Basically what ldelossa was saying.

**Comment by ldelossa** [comment]
Why do you do the:

```
        vim.cmd("wincmd c")
```

When "WinClosed" fires the window it matches for is already closed, why do you do the additional close of a window there?

**Comment by distek** [comment]
The autocmd actually triggers _before_ the window is closed, which I wasn't expecting. Found that by placing a print statement in after the loop; It print's before closing the window. I'm assuming the idea is you run some cleanup tasks for the window you're closing?

The way it is right now, it functions the way I'd expect `:q` to work. If you test it and it doesn't work that way, let me know as I might have something weird lurking in my config.

**Comment by ldelossa** [comment]
Aha! I must have read the docs wrong. 

Okay, and it appears that the event is not recursive. So I dont think youll fire an event from this event, for the same window being closed, which is good 👌

**Comment by distek** [comment]
I actually think you read the documentation correctly. I'm looking through the nvim source though and it looks like it fires the event before it actually closes the window?:
https://github.com/neovim/neovim/blob/b2bb3973d9c7f25acfead2718d74fcf5b1e4551e/src/nvim/window.c#L2776

I might be reading it incorrectly.

_Anyway_, it might be up to nvim-ide to track the current state and if the only windows open are the panels, then close neovim/the current tab.

**Comment by ldelossa** [comment]
If your autocmd there works reliably, you can shove it right into the "WorkspaceController" init function I believe: https://github.com/ldelossa/nvim-ide/blob/e81fbd084f10b92bb6a4f62155e0fa1edbee9c7e/lua/ide/workspaces/workspace_controller.lua#L227

Guard it with a config variable, and lets see how that goes?

**Comment by distek** [comment]
Let me test it more at work today and I'll give you a yay or nay on that.

**Comment by ldelossa** [comment]
Sounds great.

**Comment by distek** [comment]
Broke almost immediately.

Played with it throughout the day when I could, came up with this:
```lua
vim.api.nvim_create_autocmd("WinEnter", {
    pattern = {
        "*"
    },

    callback = function()
        local winCount = 0
        local compWinCount = 0
        for _, v in ipairs(vim.api.nvim_list_wins()) do
            local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))

            if string.find(name, "component://*") then
                compWinCount = compWinCount + 1
            end

            winCount = winCount + 1
        end

        if stdBufCount == compWinCount then
            vim.cmd("qa")
        end
    end
})
```

Using `WinEnter` made sense since when you're quitting in the last "normal" window, it will close the window (as we talked about) and will run after the `:q`. I _think_ this is the best route. 
My only concern: Though it doesn't seem to slow anything down when moving between windows, it is running two separate commands + a loop. If it gets integrated in to the codebase, we could probably instead use the `.is_open()` to get which/how many panels are open, and then just compare that to the number returned by `#vim.api.nvim_list_wins()`

**Comment by ldelossa** [comment]
Hmm, maybe this is a bit more optimized? Basically, just try to quit ASAP when you see a window that's not a "component://" window. 

```
vim.api.nvim_create_autocmd("WinEnter", {
    pattern = {
        "*"
    },

    callback = function()
       -- optimize exit
      local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))
      if not string.find(name, "component://*") then
          return
      end
      
      -- we are in a component win, search other wins to see if there are 
      -- any non-component wins.
      for _, v in ipairs(vim.api.nvim_list_wins()) do
            local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))
            if not string.find(name, "component://*") then
                return
            end
        end
      
        -- only component wins left, exit
        vim.cmd("qa")
    end
})
```

**Comment by distek** [comment]
> You could keep track of and then check if the number of nvim-ide windows is equal to the total number of windows

That's what I was doing in the last iteration, but I think ldelossa has an idea there so this is my likely final iteration:
```lua
vim.api.nvim_create_autocmd("WinEnter", {
    pattern = {
        "*"
    },

    callback = function()
        if not string.find(vim.fn.bufname(vim.api.nvim_win_get_buf(0)), "component://*") then
            return
        end

        for _, v in ipairs(vim.api.nvim_list_wins()) do
            if not string.find(vim.fn.bufname(vim.api.nvim_win_get_buf(v)), "component://*") then
                return
            end
        end

        vim.cmd("qa")
    end
})
```

**Comment by mrjones2014** [comment]
This doesn't work for me

**Comment by ldelossa** [comment]
Odd, works on my end. What happens for you?

**Comment by mrjones2014** [comment]
It just doesn't seem to do anything. Can we put the autocmds into an augroup so I can inspect just that one augroup to further debug?

**Comment by distek** [comment]
@mrjones2014 Not sure if this is your issue but I had to recompile with Packer to get everything working correctly. Also after changing `auto_close` to false (to test that it would behave as expected)

**Comment by mrjones2014** [comment]
Hmm, I tried changing `auto_close = false` then `:PackerCompile` then change back `auto_close = true` then `:PackerCompile` and still no luck.

**Comment by distek** [comment]
Have to ask, just to be sure, but did you make sure you're back on main?

**Comment by mrjones2014** [comment]
I'm using my fork currently since I'm working on a PR, but I synced the fork with the main repo and merged main into my branch, so the changes are definitely there. I can see the changes in my local codebase.

**Comment by mrjones2014** [comment]
I still can't get this working 🤔

**Comment by distek** [comment]
I'm super unsure as to whats happening there. Its working fine on my work laptop as well, so that's both Mac and Linux that its working fine on for me. Maybe try removing the `packer_compiled.lua` and compile once more? I cant think of what else would cause it to not work beyond that or maybe a bad merge. But the PRs look fine to me

**Comment by mrjones2014** [comment]
I think I might've figured it out. The autocmd needs to be a little more judicious. I think we need to not only check windows, but also check whether the window is a "normal" buffer.

For example, I have this little floating window that shows LSP progress, and `nvim-notify` uses floating windows.

I think the autocmd needs to check if there are any _non-floating_ windows.

![image](https://user-images.githubusercontent.com/8648891/204624584-5460b943-a487-4972-8bec-2abe209b7761.png)

**Comment by distek** [comment]
AH! Okay that makes perfect sense. I don't have any additional floats ever so I hadn't thought of that. If you want, submit a fix for that please. If not, I can submit a fix later today.

**Comment by mrjones2014** [comment]
I'm working on a fix but it's more complicated to catch all edge cases than I thought.

**Comment by mrjones2014** [comment]
I'm actually not sure if there is a way to solve this in a generic way that will work for everyone 🤔

**Comment by distek** [comment]
I wonder if my second to last iteration would help (where we count the current windows)? Except skip any window thats floating

**Comment by mrjones2014** [comment]
There are some edge cases that won't catch. For example noice.nvim has some windows that are sorta hidden somehow.

I think for myself I'll just use `:qa` ¯\\\_(ツ)_/¯

**Comment by distek** [comment]
Is it getting too much into the weeds if we give the user the ability to specify a list of buffer names to ignore?

**Comment by mrjones2014** [comment]
Probably buffer types or file types would better than buffer names but I think it’s reasonable

**Comment by ldelossa** [comment]
ooof, It's be nice if we can figure this out with a blacklist. 

@mrjones2014 does this not handle the edge cases?

```
To check whether a window is floating, check whether the `relative` option in
its config is non-empty:  

    if vim.api.nvim_win_get_config(window_id).relative ~= '' then
      -- window with this window_id is floating
    end
```

**Comment by distek** [comment]
I can play around with this later today if mrjones cant get to it

@mrjones2014 what is that floating LSP info plugin? Ill install that and noice to sort of replicate your environment

**Comment by mrjones2014** [comment]
That checks if there are floating windows but like I said some plugins have some windows that are sorta “hidden”.

the LSP status floating thing also comes from noice.nvim

**Comment by ldelossa** [comment]
Hmm, any more clarity on "kinda hidden" ?

**Comment by mrjones2014** [comment]
Not sure exactly, but when I list windows via the API, it lists windows than I don’t seem to be able to find anywhere visually. I can do some more debugging when I’m back at my desk tomorrow.

**Comment by ldelossa** [comment]
Argh, annoying. Okay.

**Comment by distek** [comment]
@mrjones2014 Could you try replacing the autocmd from this PR with the following and see if it works as expected?:
```diff
@@ -232,14 +232,9 @@ function WorkspaceController.new(config)
     -- Exit's vim if WinEnter was triggered and the only remaining windows are
     -- component windows.
     function self.auto_close_autocmd()
-        if not string.find(vim.fn.bufname(vim.api.nvim_win_get_buf(0)),
-            "component://*") then
-            return
-        end
-
         for _, v in ipairs(vim.api.nvim_list_wins()) do
-            if not string.find(vim.fn.bufname(vim.api.nvim_win_get_buf(v)),
-                "component://*") then
+            local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))
+            if not string.find(name, "component://*") and name ~= "" then
                 return
             end
         end

```

I think noice is just creating a bunch of windows (along with nvim-notify) that are unnamed buffers strictly to display data of some type

**Comment by mrjones2014** [comment]
This "works", but it makes it so that if I open Neovim, then try to launch Telescope to find a file, it closes Neovim because `WinEnter` has launched for the Telescope floating window, which also has no name.

Btw you should use `vim.api.nvim_buf_get_name` over `vim.fn.bufname` because of `:h api-fast`

**Comment by distek** [comment]
I think this might be more appropriate then?:
```lua
    function self.auto_close_autocmd()
        if not string.find(vim.fn.bufname(vim.api.nvim_win_get_buf(0)),
            "component://*") then
            return
        end

        for _, v in ipairs(vim.api.nvim_list_wins()) do
            local name = vim.fn.bufname(vim.api.nvim_win_get_buf(v))
            if not string.find(name, "component://*") and name ~= "" then
                return
            end
        end

        vim.cmd("qa")
    end
```
That first if should make it so you don't have that issue.

From what I just tested: Opening nvim without a file and using telescope works without issue, after selecting a file and having a notify window open, it closed as expected. Hopefully, maybe, that'll work correctly for you as well? I have noice installed now and it seems to be working fine along side the above autocmd.

> Btw you should use vim.api.nvim_buf_get_name over vim.fn.bufname because of :h api-fast
Nice, thanks! Should everything work out with the above, I'll change over to that.

**Comment by mrjones2014** [comment]
That seems to work!!

**Comment by ldelossa** [comment]
nice!

**Comment by ldelossa** [comment]
oof @distek sorry to tell you, this now closes my whole nvim process when I enter an nvim-ide window... reverting to `eb307bccb3a594fb9669f1e6ed25e8386310a80f` fixes the issue. I'm going to need to revert these commits for the time being.

**Comment by distek** [comment]
I seem to only be getting it if nvim was opened without a file (which isn't acceptable but I was testing _with_ a file, I realize now).

I'm kind of thinking we should just remove the whole thing for the moment and approach it differently. This seems to have too many edge cases that need to be caught.

**Comment by mrjones2014** [comment]
Yeah and every user will have different edge case depending on their other plugins and config. Maybe we should put an example in the wiki and people can use that as a starting point to just write their own autocmd?

**Comment by ldelossa** [comment]
Yeah, we can just rip it out for now, and keep this issue open.

**Comment by ldelossa** [comment]
> Yeah and every user will have different edge case depending on their other plugins and config. Maybe we should put an example in the wiki and people can use that as a starting point to just write their own autocmd?

also not a terrible idea.

**Comment by distek** [comment]
https://github.com/ldelossa/nvim-ide/pull/53

**Comment by distek** [comment]
Hey all! Been a while.

So I ended up writing a plugin to solve this for myself. It's been working pretty solidly for the past month or so and figured I'd share what I ended up doing.

The plugin-ish thing I wrote was due to how vim/neovim handles events. Basically, if you set up an autocmd for an event of whatever type (i.e. WinClosed), the event is fired prior to the event's conclusion. So a WinClosed event takes place prior to actually entering the next window. At least this is what I gathered from reading the neovim source, but it seems to track with how all this ended up working out.

The plugin-ish thing:
https://github.com/distek/aftermath.nvim

The solution I came up with:
```lua
local addHook = require("aftermath").addHook

addHook({
	id = "auto-close-nvim-ide",
	desc = "Automatically close nvim if only remaining windows are nvim-ide components",
	event = "WinEnter",
	run = function()
		local newWinName = vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(0))

		if not string.find(newWinName, "component://*") and not string.find(newWinName, "term://") then
			return
		end

		local compCount, winCount = Util.compVsWinCount()

		if winCount == compCount then
			vim.cmd("qa")
		end
	end,
})
```

This hasn't failed for me as of yet, regardless of what I end up doing when exiting an editing session. The functionality of the plugin is super simple and the whole implementation is less than 100 LOC. Not sure if it'd be worth integrating or just mentioning elsewhere (start a wiki?), but figured I'd document what's been working for me all this time.

P.s. the `Util.compVsWinCount` is:
```lua
Util.compVsWinCount = function()
	local winCount = 0
	local compCount = 0

	for _, v in ipairs(vim.api.nvim_list_wins()) do
		local name = vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(v))

		if vim.api.nvim_win_get_config(v).relative == "" then
			if string.find(name, "component://*") or string.find(name, "term://") then
				compCount = compCount + 1
			end
			winCount = winCount + 1
		end
	end
	return compCount, winCount
end
```

I just moved it out as I ended up using it elsewhere in my config.

**Comment by ldelossa** [comment]
Hey all in this thread. 

I was just toying around a bit and I think I found a solution to this. 

There is now a new config flag which defaults to 'close' 

```
	-- workspaces config
	workspaces = {
		-- which panels to open by default, one of: 'left', 'right', 'both', 'none'
		auto_open = "left",
		-- How nvim-ide should handle a ":q" on the last regular (non nvim-ide, non popup) window.
		-- "close" - when the last window is closed perform a ":wqa!", closing nvim-ide
		-- panels as well
		-- "block" - block the last window from closing by creating a new split.
		-- nvim-ide panels must be hidden before closing the last window.
		on_quit = "close",
	},
``` 

The default value is `close`. If NVIM-IDE can detect only one other window exists, other then themselves, it will close neovim. You can also use 'block' as a safer method which won't close Neovim until thee nvim-ide panels are hidden. 

Anyone want test this out?

**Comment by ldelossa** [comment]
So long-open issue seems to be closed now with the latest commits. Feel free to open it. I'm not 100% sure this plays nice with all plugins which utilize long-lasting windows, so there maybe some edge cases.
