### ISSUE TITLE
ToggleTerm/Terminal floatting window

### ISSUE THREAD

**Issue by prdanelli** [ldelossa/nvim-ide#15]
I've found a few "issues" while testing and i'm adding them individually so as to keep the discussions focused. 

t seems to prevent floating terminal windows from opening - I use [Toggle Term](https://github.com/akinsho/toggleterm.nvim) to add shortcuts for terminal programs like Lazygit that open in a floating window and they seem to immediately close with Nvim-IDE open, but without the terminal panel being open, the floating terminal windows act normally.

**Comment by sboesebeck** [comment]
I also use Toggle Term and Lazygit - no problem here with nvim-ide!

**Comment by ldelossa** [comment]
Hmm, i cant say I have any issues with floating windows. 

Can you confirm with all your other plugins off?

**Comment by ldelossa** [comment]
@prdanelli - I'm going to respectively close this for now. I've been using this plugin as a daily driver for awhile now and I do not have this issue. 

If you experience this issue when all other plugins are closed, feel free to re-open.
