### ISSUE TITLE
Support for detatched git worktrees

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#20]
When editing my Neovim config, the git root is located at `~`, and the `.git` repo directory is at `~/.dotfiles`. With `gitsigns` I can do:

```lua
require('gisigns').setup({
  worktrees = {
     {
      toplevel = vim.env.HOME,
      gitdir = string.format('%s/.dotfiles', vim.env.HOME),
     },
  }
})

**Comment by ldelossa** [comment]
Hey @mrjones2014 

I do a lot of my own work in git worktrees, and I haven't experienced any issues so far with the current components not working within then. 

Why is this necessary?

**Comment by mrjones2014** [comment]
My repo root is at `~` and the `.git` repo folder is at `~/.dotfiles` — when I open the directory `~/.config/nvim` for example, the git components don’t show anything.

maybe it’s because I’m not at the repo root, but in a subdirectory of the repo root?

**Comment by ldelossa** [comment]
Can you test at the repo's root?

Tho that would be odd, since all the git cli commands work from a sub directory. It is possible the embedded git cli is doing something weird.

**Comment by mrjones2014** [comment]
I get the same behavior when opening the repo root

**Comment by ldelossa** [comment]
Ah, you know. I dont think ive used "detached" worktrees before. I see now, its a bit different then a standard worktree. Ill look into this.

**Comment by mrjones2014** [comment]
I don't have this use-case anymore; I use Nix and `home-manager` to manage my dotfiles now, so I don't have that weird detached worktree workflow anymore, my dotfiles just live at `~/git/dotfiles` and `home-manager` handles putting everything in the right place.

Feel free to reopen if someone else still needs this.
