### ISSUE TITLE
docs: Add more information on installing via a package manager

### ISSUE THREAD

**Issue by exdx** [ldelossa/nvim-ide#23]
The statement "Get the plugin via your favorite plugin manager" in the README likely makes a lot of sense to advanced neovim users. But if the user is newer to neovim, and doesn't necessarily have a plugin manager, it's not very helpful. It would be great to provide some additional context:
* What package managers are available (and which one is preferred)? 
* What's the name of the package to install? Is it `nvim-ide`? 
* Are there any additional caveats? For example, does installing on windows work OOTB?

**Comment by ldelossa** [comment]
Good call. 

I don't think i'd like to list all the package managers in the neovim ecosystem. And I only really use plug, so maybe I'll put an example of that in the Readme, and users of other plugin managers can add their own examples.

**Comment by exdx** [comment]
Yes, I think that's a good way to go

**Comment by ldelossa** [comment]
I think Peppo would approve.

**Comment by mrjones2014** [comment]
I think the majority of users these days use `packer.nvim` so its probably worth listing both `vim-plug` and `packer.nvim` instructions. Those are the two most popular by far.

**Comment by exdx** [comment]
I can take a look at this. I'm familiar with both those projects, but barely lol. Will try to have something up over the weekend.

**Comment by exdx** [comment]
Addressed in the linked PR.
