### ISSUE TITLE
Files should still be sorted alphabetically when using `list_directories_first`

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#25]
Related to the option I added. Since `table.sort` in Lua is an unstable sort algorithm, we'll need to use a stable sort.

I can put up a PR for this soonish.

![image](https://user-images.githubusercontent.com/8648891/204353184-c9f7fd55-9a1c-4de5-b257-3071aa8d7417.png)

**Comment by ldelossa** [comment]
Yup, I had a bit of concern over this, but I don't plan on using this option so I didnt hold the PR back. Feel free to fix whenever.
