### ISSUE TITLE
Add a `.stylua.toml` file and ensure all Lua files match format

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#27]
Thoughts @ldelossa ?

If you're into the idea, I can submit a PR and set up checking via GitHub Actions. I can write the `workflow.yml`, and then you'd just need to set it as a required workflow to pass for PRs in repo settings.

**Comment by ldelossa** [comment]
I usually just use the LSP's formatter. Maybe this will be better as I think most use the same Lua lsp, and it would have all developers formatting the code similarly, without additional tools.

**Comment by mrjones2014** [comment]
Ah, gotcha. I have my editor using stylua by default but I can tweak my config to use LSP formatter if no `.stylua.toml` is found 👍
