### ISSUE TITLE
`Buffers` built-in component

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#28]
VS Code has an option to show currently opened files as a separate list from the file tree, I'd like to replace `barbar.nvim` with this plugin.

![image](https://user-images.githubusercontent.com/8648891/204356031-5e48879f-8ff7-4b2a-a5f4-be1922f9e866.png)

**Comment by ldelossa** [comment]
Yup, was just wanting to do this tonight. Feel free to take it on! I believe its a solid fit for the default set of components.

**Comment by mrjones2014** [comment]
I can work on a PR for it 👍

**Comment by ldelossa** [comment]
awesome! if anything comes feel free to bring it up here.

**Comment by mrjones2014** [comment]
Could you point me to where highlights are handled? I've got a very basic implementation but it's currently not handling icons properly and not highlighting anything.

**Comment by ldelossa** [comment]
All components implement a "post_win_create" hook, which the panel calls when creating the plugins window. Then theres a small helper function which sets highlights usually called there: 

https://github.com/ldelossa/nvim-ide/blob/14071cf55e389829b829331fababc82930f7750b/lua/ide/components/commits/component.lua#L175

**Comment by ldelossa** [comment]
Although, maybe the Explorer component is a better example. Since you can use webdev icons. 

https://github.com/ldelossa/nvim-ide/blob/14071cf55e389829b829331fababc82930f7750b/lua/ide/components/explorer/component.lua#L158
