### ISSUE TITLE
Logging needs attention

### ISSUE THREAD

**Issue by ldelossa** [ldelossa/nvim-ide#30]
There is a logger package in `ide.logger` module. 

Currently, its logging all levels unconditionally. We should set a log level in the config and log everything from that level and above. The logger calls should no-op if they are used and the given log level (and higher) is not specified in the config.

Additionally, a logging pass is needed. A logger is setup in a lot of functions, but never used, since I got enticed by adding features :grin:

**Comment by BeeverFeever** [comment]
Hey I was just wondering, how would I access the value of, for example, the `log_level` option in the config, from the logger.lua file?

**Comment by BeeverFeever** [comment]
How can I get the `log_level` value from the config into the logger.lua file?

**Comment by ldelossa** [comment]
Here is an example in "workspaces.lua" https://github.com/ldelossa/nvim-ide/blob/ca17635e368df7b0b2cec303213d40f0dca7522c/lua/ide/workspaces/workspace.lua#L44

As you can see, you should be able to access config like a global with "require("ide").config". Im nit sure why this wouldnt work for you.

**Comment by BeeverFeever** [comment]
Hmm ok, i'll see if i might have been doing something wrong. thanks

**Comment by BeeverFeever** [comment]
After playing around with things I still can't get the require to work. The error it gives me is `loop or previous error loading module 'ide'` and I can't find anywhere where it would be a loop (unless I don't completely understand lua's require system).

**Comment by distek** [comment]
Hey @ldelossa I was looking in to this and I see what BeeverFeever was saying; There's a module dep loop when it comes to requiring 'ide' inside of logger due to the panels already requiring it.

I believe we talked about it before, but how would you feel about if, instead of obtaining a copy of the config in whichever modules need it, we global the config and copy in to it on init so we can just call `IDEConfig.whatever` instead?

**Comment by ldelossa** [comment]
If we move config out of init.lua, to its own file, and update all the imports, this solves the issue, right? 

The config module can be "export only" which should break any loops.

**Comment by distek** [comment]
I think that will work. Do you want a PR for it?

**Comment by ldelossa** [comment]
Yup!

**Comment by distek** [comment]
@BeeverFeever Do you want to work on this? If not, I can go at it later today.

**Comment by BeeverFeever** [comment]
I will give it a quick try but you might have to do it because I'm going away and won't be able to work on it.

**Comment by distek** [comment]
Sounds good, just let me know.

**Comment by BeeverFeever** [comment]
Ok will do.

**Comment by BeeverFeever** [comment]
Quick question, with the panel_groups in the config, do you think they should just be set in the setup function in `init.lua` before mergeing the users config? Otherwise a require is needed in `config.lua`(the new file with the default config)

**Comment by distek** [comment]
I think doing the requires in the `config.lua` is fine? Maybe by doing something like:
```
local bufferlist      = require('ide.components.bufferlist').Name
```

**Comment by BeeverFeever** [comment]
Ok I'll see if that might work.

**Comment by ldelossa** [comment]
Should work, the init.lua files in each component dir dont need to refer to config.

**Comment by BeeverFeever** [comment]
It still doesn't work. The only way I can think of getting it to work is by hard coding the values in. So for example you just put the name of the components you want as a string rather than using a require.

**Comment by BeeverFeever** [comment]
@ldelossa The problem is that the components are referring to logger though.

**Comment by ldelossa** [comment]
@BeeverFeever yes I see. 

https://github.com/ldelossa/nvim-ide/compare/main...refactor-for-logger - Here is a base refactor, I think this is fine, we'll just expose a method in the logger which sets the log level, and not give it the full config. 

Want to use this as base to work the rest of the PR out?

**Comment by BeeverFeever** [comment]
Yeah sure, that looks pretty good.

**Comment by BeeverFeever** [comment]
@ldelossa Just wondering, do you want to use the `vim.log.levels.` for the logger levels or could I go with something where we set a table of log levels, like:
(in logger.lua)
```
local log_levels = {
    ['debug'] = 1,
    ['error'] = 2,
    ['warning'] = 3,
    ['info'] = 4,
}
```
and then use those values to detect whether to log the message or not?

**Comment by BeeverFeever** [comment]
This is what I've got so far. BeeverFeever/nvim-ide@47225a699ef8dd1ffecb34a95faf1bc36cb6e335

**Comment by ldelossa** [comment]
The 'set_log_level' probably take either a string, or an integer. But the log_level variable should probably be an int, so you can determine if you should log with a '>' or '<' evaluation.

**Comment by BeeverFeever** [comment]
Ok sounds good. I will make those changes and tidy it up then make a pr if it looks good to you otherwise?

**Comment by BeeverFeever** [comment]
Also one more thing sorry, how would I run the logger tests?

**Comment by ldelossa** [comment]
Your diff looks fine, maybe we add a function which checks the incoming log_level variable to see if its a string or int, and attempt to return an integer. 

Then we can do one more pass which removes all the strings in favor of using `vim.log.levels` directly. If we feel thats better.

**Comment by BeeverFeever** [comment]
Yeah that sounds better than using strings. Just wanted to make sure, did you want it to only log the level that is set by `Logger.log_level` or did you want it to log the set level and anything 'higher' than it?

**Comment by ldelossa** [comment]
Log level and higher. So if you set for "debug" it should log debug and all higher levels. 

Tests are best effort so far. You can add them if youd like.

**Comment by BeeverFeever** [comment]
Ok thanks, how would I run the tests?

**Comment by ldelossa** [comment]
We don't have automated tests at this point. Most of the time I run tests manually to confirm something works.

**Comment by BeeverFeever** [comment]
Ahh ok fair enough

**Comment by BeeverFeever** [comment]
I have done a bit but I ran into a problem where it seemed like `Logger.log_level` was just being set to nil and I was getting an error saying `attempt to compare number with nil`. I have no clue why this is happening.

BeeverFeever/nvim-ide@020a211cf6b8a13fd0b9e1937469249528abbe82
I hate leaving this broken right now but I just don't have any more time right now to work on it. If someone else wants to look at it they can or I will pick it up again in a couple days to see if I can get it to work.

**Comment by ldelossa** [comment]
@distek did you want to take it from here? If not I will. 

@BeeverFeever no worries - glad you got to take a stab at it.

**Comment by ldelossa** [comment]
Still needs an over-all logging pass, to place info logs in more appropriate places, but the leveled logging stuff is done.
