### ISSUE TITLE
How to get the component windows back if I close them?

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#35]
I didn’t expect `<ESC>` to close the single window, IMO it should toggle the whole sidebar.

anyway, if I accidentally close one or more component windows, is there an easy way to get them back and fully restore the window layout?

**Comment by ldelossa** [comment]
Every component exposes a "Focus" command, which "unhides" the component and puts your mouse in it. 

For example, "Workspace Explorer Focus". 

You should be able to remap the "hide" keymap for components with config overrides.

**Comment by mrjones2014** [comment]
Okay perfect. Is there a way to bind sort of "global" keymaps? Not truly "global" but keymaps that will apply to all `nvim-ide` windows.

For example, I'd like to remap `<ESC>` to toggle the currently focused nvim-ide sidebar, but only in the buffers that are part of the sidebar (e.g. if I'm in a normal file buffer it shouldn't do that).

**Comment by ldelossa** [comment]
I think theres two different things here.

1. Unfortunately, there is no way to apply a keymap across multiple components. This is in my mind too, as overriding say "hide" would have to be done at ever component in the "components" override section. 

2. Every component structure should keep a reference to the panel. So one could create a command within the component that calls close on their associated panel. This would selectively toggle the the panel only when inside a component, and have it only toggle that components panel.

**Comment by mrjones2014** [comment]
I think we can close this as what I'm looking for can be done with a bit of user config

**Comment by mrjones2014** [comment]
How does `<Esc>` close the window? I'm trying to figure that out so I can disable that behavior but I don't see `<Esc>` anywhere in the code 🤔

**Comment by ldelossa** [comment]
lol grep for <ctrl-]>

nice easter egg right.

**Comment by mrjones2014** [comment]
Here's what I ended up doing, just disabling the `hide` keymap and setting a different keymap to toggle the whole sidebar:

```lua
local explorer = require('ide.components.explorer')
local outline = require('ide.components.outline')
local bufferlist = require('ide.components.bufferlist')
require('ide').setup({
  components = {
    [explorer.Name] = {
      list_directories_first = true,
      show_file_permissions = false,
      keymaps = {
        hide = '<NOP>',
      },
    },
    [outline.Name] = {
      keymaps = {
        hide = '<NOP>',
      },
    },
  },
  panel_groups = {
    explorer = { bufferlist.Name, explorer.Name, outline.Name },
  },
})

vim.keymap.set('n', '<F3>', ':Workspace LeftPanelToggle<CR>', {})
```

**Comment by ldelossa** [comment]
lol, its going to become a pain in the ass to set keymaps individually for every component, isn't it?

**Comment by mrjones2014** [comment]
Yeah lol. I'd wanna always disable the `hide` keymap since for my workflow I'd want to always keep the same sidebar layouts, and just toggle the full sidebars.

Maybe there should be an option like `freeze_layout` and then in that case, the `hide` keymap instead toggles the whole sidebar or something?

Or alternatively a way to set keymaps that apply to all components.

**Comment by ldelossa** [comment]
Yeah, I think we may want a "global_keymap" in the "components" black, and then in just merge that global keymap with each component's keymaps field on component construction?

**Comment by mrjones2014** [comment]
Yeah that sounds good to me.
