### ISSUE TITLE
Help docs directory needs to be moved to make it available

### ISSUE THREAD

**Issue by distek** [ldelossa/nvim-ide#4]
Hello!

It seems if the docs are in `nvim-ide/docs`, they are not available within vim, but renaming the docs dir to `doc` seems to do the trick. So:
```
mv docs doc
```
to clarify.

Do you have them available within nvim while they're under the `docs` dir?

**Comment by ldelossa** [comment]
Whoops, i think youre right. Wanna send in a PR that renames it? 

If not i'll fix in a bit. AFK.
