### ISSUE TITLE
Git commit component

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#40]
It would be neat to have a component like VS Code's commit window, where you can type a message and commit.

![image](https://user-images.githubusercontent.com/8648891/204610073-f58b8ac9-2c77-472e-beb4-f24c44340aae.png)

**Comment by ldelossa** [comment]
So, i reuse the buffer feature for this. If youre using the TerminalBrowser component alongside the "Commits" comment, you can commit directly from that component, and it will automatically open the terminal in an editor to commit the message. 

IMO this is nicer then the vscode window which was always kinda clunky for me. 

This maybe a good out-of-tree component tho?

**Comment by mrjones2014** [comment]
Oh I actually like the terminal workflow you described better.
