### ISSUE TITLE
Prevent polluting global Lua namespace

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#42]
I noticed that in most of the modules, you're just doing something like:

```lua
Whatever = {}

-- some stuff

return Whatever
```

This creates a _global_ variable, which isn't really ideal. Unless you have some specific reason they need to be globals, you should do:

```lua
local Whatever = {}

-- some stuff

return Whatever
```

**Comment by ldelossa** [comment]
Yup youre right, no need for globals. This was probably a typo that got copy pasta'd all over the place, since a lot of the code is self similar and I s/thing/that quite often.

**Comment by mrjones2014** [comment]
There are tons of other Lua warnings too if you have Lua diagnostics set up, but I'll just focus on global variables for now.

**Comment by ldelossa** [comment]
Probably a lot of var redeclars due to closure usage, which i disable
