### ISSUE TITLE
Prevent files from taking over sidebar buffers

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#44]
Example:

![CleanShot 2022-11-29 at 15 04 00](https://user-images.githubusercontent.com/8648891/204636661-6733d9de-1fae-4a2e-ae74-109b11d5b289.gif)

Example code implementing such behavior: https://github.com/mrjones2014/op.nvim/blob/master/lua/op/sidebar/init.lua#L253

**Comment by mrjones2014** [comment]
If a new buffer is opened in an nvim-ide window, reset the window and put the newly opened buffer into the last non-nvim-ide buffer, or a new window if there are none.

**Comment by ldelossa** [comment]
yes! I always wantd to do something similar, but haven't put time into it. There was also some conversation of having the mainline neovim code offer a "lockdown window" option, but I don't think that went anywhere. 

We have a helper function which will find the "next appropriate window" here: https://github.com/ldelossa/nvim-ide/blob/6121615801850ab692df76e2d216a45935dc1711/lua/ide/workspaces/workspace.lua#L340 which can be used for 
>put the newly opened buffer into the last non-nvim-ide buffer, or a new window if there are none.

**Comment by technicalpickles** [comment]
I've run into this too. The main way I've been reproducing is using `Telescope find_files` in one of the components, not thinking about where the cursor is focused.

I just tested nvim-tree, and it seems to do the right thing. If you watch closely, you can see it starts to open the buffer, and then moves it over.

**Comment by mrjones2014** [comment]
this has been bothering me a ton today so I'll submit a PR for it shortly lol
