### ISSUE TITLE
file explorer should have an option to sort directories above files

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#5]
In file explorer there should be an option to make subdirectories be sorted to the top of the directory listing, above files.

**Comment by ldelossa** [comment]
Ive never found this too useful, but if we get enough thumbs up ill take a look. TBH, low on the priority.

**Comment by mrjones2014** [comment]
Would you accept a PR implementing it?

**Comment by ldelossa** [comment]
Yup, as long as its an option and its simple enough.
