### ISSUE TITLE
outline component errors with "attempt to index field 'cursor' (a nil value)" when switching buffers

### ISSUE THREAD

**Issue by technicalpickles** [ldelossa/nvim-ide#54]
I get this error anytime I switch between buffers:

```
Error executing vim. schedule lua callback:
stack traceback: • /start/nvim-ide/lua/ide/components/outline/component.lua:161: attempt to index field 'cursor' ( a nil value)
.../start/nvim-ide/lua/ide/components/outline/component lua: 161: in function ' build outline'
./start/nvim-ide/lua/ide/components/outline/component.lua:195: in function 'callback'
.w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1958: in function 'handler'
w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1390: in function
vim/ editor. lua: in function <vim/ editor. lua:
```

![CleanShot 2022-11-30 at 09 30 24](https://user-images.githubusercontent.com/159/204822480-7b070a24-277a-4326-88ca-71b9a5f69e9f.png)

I'm getting this on Ruby files using [ruby-lsp](https://github.com/Shopify/ruby-lsp) and Lua files using sumoneko. Files without attached LSP seem unaffected.

This happens even if the symbol outline component is not shown. Is there a way to disable it in the meantime?

**Comment by ldelossa** [comment]
As a quick work around until I debug, you can add this block into your user config:

```
    -- panels defined by groups of components, user is free to redefine the defaults
    -- and/or add additional.
    panel_groups = {
        explorer = { bufferlist.Name, explorer.Name, bookmarks.Name, callhierarchy.Name, terminalbrowser.Name }
    },
```

Removes the Outline component from the explorer panel group.

**Comment by technicalpickles** [comment]
Line is: https://github.com/ldelossa/nvim-ide/blob/5ba9f236b397c3362f7c4d9fb5a9395f09a253b2/lua/ide/components/outline/component.lua#L161


I see one place that checks the cursor to be present: https://github.com/ldelossa/nvim-ide/blob/5ba9f236b397c3362f7c4d9fb5a9395f09a253b2/lua/ide/components/terminal/terminalbrowser/component.lua#LL82-L84

Maybe need a helper to that anywhere can use?

**Comment by technicalpickles** [comment]
@ldelossa the workaround worked, thanks!

**Comment by ldelossa** [comment]
I thought I had some code which ensured there ways always a cursor (even a mock one at 0,0) for a cursor. let me check this out.

**Comment by ldelossa** [comment]
Its odd to me this only happens with the Outline component, because the same code which shoots out an error is all over the place in the code base.

**Comment by ldelossa** [comment]
hey @technicalpickles are you able to try out the following branch?
https://github.com/ldelossa/nvim-ide/tree/no-cursor-restore

**Comment by technicalpickles** [comment]
@ldelossa that looks like it fixes it, thanks!
