### ISSUE TITLE
Expose More of the API

### ISSUE THREAD

**Issue by distek** [ldelossa/nvim-ide#66]
I'm not sure how much of an undertaking this would be.

Idea is basically exposing more of the underlying API.

One way to maybe go about this is to just expose a `get` and `set` for certain options at the top level of the various elements (workspace, panel, and components).

End result being something like:
`Workspace.panels.set("left", "git")`
or
`Workspace.panel[pos].get("is_open")` 
(not really sure the best way to handle it, but I figure sanitizing user input is probably needed)

This would allow for a much more script-able environment.

Few ideas where this would be nice:
- Map swapping left and right panels without needing the select UI
- Check if a panel is open so user can do some related function if desired
- Insert/remove components from a group on-the-fly
- New named terminal running a specific command, like how the commit functionality works

Just thoughts right now! Let me know what you think.

**Comment by BeeverFeever** [comment]
@ldelossa If you think this is a good idea I was thinking of working on it?

**Comment by ldelossa** [comment]
Before writing out a new API surface can you explain rather what features/scripting ability youd like in detail? 

Im wondering if the things you may want to accomplish are available, but via different apis that you havent quite explored yet.

**Comment by ldelossa** [comment]
The only two things that cant be done is: 

Insert/remove components from a group on-the-fly
New named terminal running a specific command, like how the commit functionality works

which dont seem to warrant a new API surface? They are just desired features.

**Comment by BeeverFeever** [comment]
Yeah I agree, those don't really need a completely new API surface.

**Comment by distek** [comment]
Sorry for the super late response. I think I just hadn't explored as much. The new named terminal part would be fantastic, but shouldn't need to expose much, just added on to the current route I think: 

- No args is a regular term, additional named args (`name=somename cmd=somecommand`) for a specific command term.
- Leaving off the name uses the command path as the name.

I can open a separate issue for that and we can discard this one.

**Comment by ldelossa** [comment]
@distek sounds good.
