### ISSUE TITLE
offset for bufferline.nvim

### ISSUE THREAD

**Issue by technicalpickles** [ldelossa/nvim-ide#67]
If you are using [bufferline.nvim](https://github.com/akinsho/bufferline.nvim), by you'll end up with the first tab right above the left hand panel:

![CleanShot 2022-12-04 at 15 10 56](https://user-images.githubusercontent.com/159/205513157-bed8dbbc-d9d8-4aaf-9a92-e309e9d5193d.png)

There's an option to offset this, but requires a bit of extra configuration:

```lua
require("bufferline").setup({
	options = {
		offsets = {
                         -- you might already have this if you've used nvim-tree
			{
				filetype = "NvimTree",
				text = "",
				highlight = "Directory",
				text_align = "left",
			},
                         -- add this
			{
				filetype = "filetree",
				text = "",
				highlight = "Explorer",
				text_align = "left",
			}
		},
	},
})
```

Afterwards, it looks like this:

![CleanShot 2022-12-04 at 15 18 10](https://user-images.githubusercontent.com/159/205513465-c2d24208-8d5f-4268-9bda-1fd4502f44fa.png)

I'm not sure where the boundaries lie between these plugins, if it should account for it, or update the other plugin or what, but wanted to note it as something users may run into.

**Comment by BeeverFeever** [comment]
Just my thoughts about this. I think the default position of bufferline looks perfectly fine. Unless it is possible to have the left hand panel come all the way up to the top of the screen so that there isn't an empty space/line above it. 
Maybe just some documentation specific to bufferline users would be useful?

**Comment by ldelossa** [comment]
This is really much more about bufferline and now nvim-ide. So im not sure this is the right place for this issue. Feel free to add a small snippet in the nvim-ide.txt about this tho.
