### ISSUE TITLE
"E37: No write since last change" and "E162: No write since last change for buffer "component://Explorer:1026:1" (and others)

### ISSUE THREAD

**Issue by technicalpickles** [ldelossa/nvim-ide#68]
I've been noticing this error when trying to quit after using a panel. I end up needing to `:qa!` to exit, otherwise new component buffers are created with updates. Here's an example:

![CleanShot 2022-12-04 at 15 27 06](https://user-images.githubusercontent.com/159/205513990-5ba93a6f-a090-4171-a593-f3c0e65c0670.gif)

Reproduction steps:
- open nvim
- edit a single file
- `:Workspace LeftPanelToggle`
- `:q` in original file
- `:q` in panel
- `:qa` to try to close everything
- `:qa!` to really close everything

**Comment by ldelossa** [comment]
I cannot reproduce this issue. 

If you still run into this please re-open and I can attempt to reproduce.
