### ISSUE TITLE
non-zero status code: 128  <file>   is outside repository at <dir>

### ISSUE THREAD

**Issue by avucic** [ldelossa/nvim-ide#72]
Hi, thanks for the great plugin :)

I found this error when I try to edit a file that doesn't belong to the current repository

**Comment by ldelossa** [comment]
This could be fixed with latest commit, can you update your plugin?

**Comment by avucic** [comment]
Unfortunately, I still get that error. Is there a log from which I can grab the full message?

**Comment by ldelossa** [comment]
There is a running log at "Workspace OpenLog" 

Logging is a WIP, but any cli commands will be logged there. 

Can you post the full error message?

**Comment by ldelossa** [comment]
Okay I see what's going on here, we are attempting to perform a git log for a file that's on the file system, but isn't part of the git repo of the current workspace. 

I'll have a fix for this soon, as of right now, the errors can be ignored.

**Comment by ldelossa** [comment]
fixed, lmk if there are any issues.
