### ISSUE TITLE
File tree: `.git/` gets expanded when opening files in `.github/` directory

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#76]
When editing issue templates, CI/CD scripts, etc. under `.github/` the file tree also expands `.git/`

**Comment by ldelossa** [comment]
Yup, this is on my todo list, over selection in the aucmd which syncs the tree's expansion to the current buffer.

**Comment by rosstang** [comment]
It should fix this issue,
https://github.com/ldelossa/nvim-ide/pull/104

**Comment by mrjones2014** [comment]
Not fixed by #104

**Comment by rosstang** [comment]
Sorry. Please try this fix,
https://github.com/ldelossa/nvim-ide/pull/118

I see similar issue that when I open .gitignore, and .git is expanded. This pull request should fix the issue.
