### ISSUE TITLE
File explorer: keymaps should have a preset you can set which makes it match nvim-tree's keymaps

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#77]
I (and I think many others) are switching to this from nvim-tree. Could we get an option like `keymaps = { preset = 'nvim-tree' }` that makes it easily match nvim-tree's keymaps, instead of user having to override every keymap?

**Comment by hsheikhali1** [comment]
Love this idea!

**Comment by mrjones2014** [comment]
What about something like `keymaps = require('ide.components.explorer.presets').nvim_tree`?

**Comment by ldelossa** [comment]
LGTM, feel free to send PR for that. then if there are any NERD users, do the same as well.
