### ISSUE TITLE
automatically add new terminal instances to the UI

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#8]
If I type `:term` to open a new terminal, we should be able to use a `BufNew` autocmd or something to automatically add it to the UI

**Comment by ldelossa** [comment]
Hey there. 

Is there a good reason to use ":term" anymore? Can you use "Workspace TerminalBrowser" commands instead? 

The plugin really keeps state of terminals only opened thru it, and im not sure if keeping state for terminals outside if ones created via the plugin is the best idea.

**Comment by mrjones2014** [comment]
I suppose you’re right. I can just set up an abbreviation of needed.
