### ISSUE TITLE
The `changes` component makes my cursor blink every time I move it

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#82]
If I comment out the `changes` component in my config it stops happening, so it's coming from there. I'll investigate and see if I can do a PR.

**Comment by ldelossa** [comment]
Debugged this more. 

```
    function self.event_handler(args)
        -- if not gitutil.in_git_repo() then
        --     return
        -- end
        git.status(function(stats)
            if stats == nil then
                return
            end
            _build_tree(stats)
        end)
    end
```

Guess this should become an async function, we are probably block render thread for too long.
