### ISSUE TITLE
Explorer holds on to cwd when tab was created

### ISSUE THREAD

**Issue by distek** [ldelossa/nvim-ide#85]
Heyo.

I've started playing with the concept of never leaving vim lol In this, I've found that Explorer doesn't seem to detect when a tab's cwd changes (such as with `:tcd /somewhere/else`). Instead it holds on to whatever the cwd was when the tab was created.

Should the Explorer component pick up if the cwd has changed in a tab? Or is this outside of scope of nvim-ide.

**Comment by ldelossa** [comment]
Why would a new tab mean your CWD has changed?

**Comment by distek** [comment]
It wouldn't, but if I change the cwd with `:tcd <path>` then it would.

**Comment by distek** [comment]
Looks like explorer sets the cwd on init, so I might just need to make a customized version of explorer that updates whenever the cwd changes.

**Comment by ldelossa** [comment]
Yeah, ill look into handling "DirChanged" events.

**Comment by ldelossa** [comment]
@distek can you try the `explorer-handle` branch. I did a rough sketch of changing dirs. Can you test it out with 'tcd' 'lcd' and 'cd'. 

The idea is that a global 'cd' should reinit all the trees across all tabs, an 'tcd' should only reinit the tree that's preset in the tab the 'tcd' was called in, and a 'lcd' will reinit the tree when you swap between windows with their own directories set.

**Comment by distek** [comment]
They all work as expected! It'd be cool if `lcd` worked per buffer but I believe that is out of scope for this and would be a neovim specific issue, if anyone really wanted it.

_For me_, the way tcd works now is perfect!

**Comment by ldelossa** [comment]
Yeah the "lcd" semantics are a bit weird, tbh ive never used that before. Not sure if its uses too often in practice?

**Comment by distek** [comment]
Auto-cd for the buffer, which could be useful for some maybe? Same, though. I've never seen a use for it in my own workflow.
