### ISSUE TITLE
Error when starting more than one terminal from terminal browser

### ISSUE THREAD

**Issue by distek** [ldelossa/nvim-ide#88]
Haven't dug in to it yet, but this keeps happening every time I open a new terminal beyond the first one:
```
E5108: Error executing lua: Vim:Can only call this function in an unmodified buffer
stack traceback:
	[C]: in function 'termopen'
	...start/nvim-ide/lua/ide/components/terminal/component.lua:91: in function 'new_term'
	...ua/ide/components/terminal/terminalbrowser/component.lua:103: in function 'new_term'
	...ua/ide/components/terminal/terminalbrowser/component.lua:49: in function <...ua/ide/components/terminal/terminalbrowser/component.lua:49>
```

This happens whether I press "n" in the terminal browser, or if I call `:Workspace TerminalBrowser New`, or both.

However, the terminal browser shows multiple terminals as though there _is_ more than one, and I can rename them individually, but they all bring up the same terminal if I hit enter on them.

Hoping someone can confirm if this is just a me thing, as this hasn't happened until recently.

Edit: I _did_ just update neovim to the latest nightly. Investigating.

Edit 2: Seems like it's rather not actually creating the new buffer or the `nvim_win_set_buf` isn't working correctly for the terminal in `new_term()`. Might be a me thing, not sure. I'll play with it tomorrow.

**Comment by ldelossa** [comment]
Hey. 

I did a bisect and this issue was introduced in: https://github.com/ldelossa/nvim-ide/commit/1eaeb79fcdde2f0d3346b79343f68d3972237b7c

Reverted the commit. 

@mrjones2014 - Can you attempt this change again, but ensure other components (primarily the term component here) do not break?

**Comment by ldelossa** [comment]
@distek I pushed the revert, can you confirm term works OK now?

**Comment by mrjones2014** [comment]
Apologies, I don't use terminals in Neovim. I'll try again and test them specifically.

**Comment by distek** [comment]
@ldelossa That fixed it!

@mrjones2014 I think the just the terminal component needs to be ignored in that autocmd?

Would you like me to leave this open or close it and track that separately?

**Comment by mrjones2014** [comment]
Let's leave it open, I'll mark my PR as resolving this issue.
