### ISSUE TITLE
method textDocument/documentSymbol is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by sboesebeck** [ldelossa/nvim-ide#9]
I get this error when opening a lua file. It is not shown when `nvim-ide` not loaded or setup not called.

**Comment by mrjones2014** [comment]
This also happens when the LSP server is not yet initialized. I am guessing the component is trying to grab the outline, but it isn't available yet.

**Comment by sboesebeck** [comment]
if so, we'd have to change the call order. This is not really easy to accomplish, right?

**Comment by ldelossa** [comment]
Yeah, this is most likely this just means your LSP didnt start yet. Does it work after LSP is attached?

**Comment by mrjones2014** [comment]
It does. You just get the notification right when the buffer opens, because the LSP hasn’t initialized yet.

**Comment by ldelossa** [comment]
Hmm, i suppose the autocmds and component code could check if an LSP is attached to the buffer and just perform any action if its not.

**Comment by technicalpickles** [comment]
I ran into this too. The LSPs I'm using are ruby-ls and sumoneko, which seem to take a bit of time to start up.

I tried removing `outline` from the panel group used at startup, as well as not including a default panel group at startup, but get the same error.

Here's the full error in case it's useful:

<img width="821" alt="CleanShot 2022-11-27 at 19 43 41@2x" src="https://user-images.githubusercontent.com/159/204169448-958e4052-d036-4332-a4ab-bfb6cc1e7058.png">

**Comment by technicalpickles** [comment]
Does anyone have suggestions for working around this? I'm seeing LSP-related warnings and errors anytime I'm switching buffers because of this.

**Comment by mrjones2014** [comment]
We would need to re-check periodically as the server will probably report that it doesn't support the method until it is finished initializing.

**Comment by ldelossa** [comment]
hmm, it looks like we do actually check if an LSP is attached:

```
    function self.create_outline()
        local log = self.logger.logger_from(nil, "Component.create_outline")
        local cur_buf = vim.api.nvim_get_current_buf()
        local cur_win = vim.api.nvim_get_current_win()

        log.debug("creating outline for workspace %d buffer %d %s", self.workspace.tab, cur_buf,
            vim.api.nvim_buf_get_name(cur_buf))
        if #vim.lsp.get_active_clients({ bufnr = cur_buf }) == 0 then
            log.debug("buffer had no LSP client attached, returning.")
            return
        end
```

So its not that an LSP is not attached, its maybe that its not initialized.

**Comment by mrjones2014** [comment]
Yeah, the issue is that it is not initialized, so before actually _getting the outline data,_ we would need to check if any attached clients support the method. I think servers will report they don't support it until fully initialized.

**Comment by ldelossa** [comment]
cool, we can def try that.
