### ISSUE TITLE
Explorer: When you create a file, if cursor is over a non-expanded directory, it should create the file in the parent directory

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#90]
The current behavior is somewhat confusing.

When you cursor is over a directory, and you create a new file, if the directory is not expanded, the new file should be created with the parent node as the root.

If the directory under cursor is expanded, only then should it use that directory as the root for the new file.

**Comment by ldelossa** [comment]
I'm not sure I agree. 

To me, its confusing when you have this directory structure:

```
/a
  /b
```

With no files, and now you want to create a file in 'b'. You must expand the empty directory before creating the file, instead of just creating the file ontop of the directory.

**Comment by mrjones2014** [comment]
it could be an option.

**Comment by ldelossa** [comment]
Lets keep this open for now, and see if others come to the same determination. I don't want to option sprawl.

**Comment by mrjones2014** [comment]
I don't use the plugin anymore. Feel free to reopen if the issue persists.
