### ISSUE TITLE
More questions than problems

### ISSUE THREAD

**Issue by JjersaR** [ldelossa/nvim-ide#93]
I decided to use the plugin because of the [youtube video](https://www.youtube.com/watch?v=GcoHnB5DoFA) and now that I try it I have some doubts that I am still not able to answer are 3:

1.- How can I disable the permissions of the files and folders that the file tree shows me?
![image](https://user-images.githubusercontent.com/86206596/209587795-7c65e160-71d9-455c-9445-236950c7ca11.png)

2.- How can I make that the statusline is not shared between the panels?
![image](https://user-images.githubusercontent.com/86206596/209587822-1b2b9e06-1b1c-41fa-9150-33ab5edd06c6.png)

3.- How can I open the left side and also the terminal?
**To look like this:**
![image](https://user-images.githubusercontent.com/86206596/209588009-db1da8e7-91ff-4f5a-9aa4-c73014a725a9.png)

**Instead of this:**
![image](https://user-images.githubusercontent.com/86206596/209588040-d7e067aa-9527-4b5e-8e4c-d67411c23b32.png)

**Comment by ldelossa** [comment]
[Please create a series of Q/A for this in discussion. ](https://github.com/ldelossa/nvim-ide/discussions/categories/q-a)
